language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
  - lts/*
jobs:
  include:
    - stage: release
      deploy:
        provider: script
        script_cleanup: true
        script:
          - npm test
        after_success:
          - bash <(curl -s https://codecov.io/bash)
          - npx semantic-release
