language: node_js
node_js:
  - stable
  - lts/*
cache:
  directories:
    - node_modules
notifications:
  email: false
jobs:
  include:
    - stage: release
      script:
        - npm test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - npx semantic-release
